version: "3"

services:
  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test19
    volumes:
      - ./docker/data/mongodb:/data/db
    ports:
      - "27888:27017"
    network_mode: bridge
  redis:
    image: redis:6.2.5-buster
    restart: unless-stopped
    ports:
      - "36379:6379"
    command: >
      --requirepass test19
    network_mode: bridge
